data_asisten/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # add route from mendata Application
    path('', include('mendata.urls'))
]

mendata/urls.py
from django.urls import path

#import view-view dari mendata/views.py
from .views import index_view, detail_view, create_view, update_view, delete_view
app_name = 'mendata'
urlpatterns = [
    # url untuk halaman daftar table data
    path('', index_view, name='index'),
    # url untuk halaman detail 
    path('<int:data_id>', detail_view, name='detail'),
    # url untuk halaman tambah data
    path('create', create_view, name='create'),
     # url untuk halaman ubah data
    path('update/<int:data_id>', update_view, name='update'),
    # url untuk menghapus data
    path('delete/<int:data_id>', delete_view, name='delete'),
]

mendata/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models

class Data(models.Model):
    # define status choices/options
    class DataStatus(models.TextChoices):
        Aktif = 'Aktif', _('Aktif')
        Calon = 'Calon', _('Calon')
        Tidak_Aktif = 'Tidak Aktif', _('Tidak Aktif')
        Mantan = 'Mantan', _('Mantan')
    class AsistenStatus(models.TextChoices):
        Praktikum = 'Praktikum', _('Praktikum')
        Riset = 'Riset', _('Riset')
    
    # define columns
    nama = models.CharField(max_length=100)
    nim = models.CharField(max_length=100)
    kelas = models.CharField(max_length=100)
    jurusan = models.CharField(max_length=100)
    status_asisten = models.CharField(
        max_length=20,
        choices=AsistenStatus.choices,
        default=AsistenStatus.Praktikum
    )    
    
    status_data = models.CharField(
        max_length=20,
        choices=DataStatus.choices,
        default=DataStatus.Aktif
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # define table name
        db_table = 'data'

mendata/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

# import class Data dari file mendata/models.py
from .models import Data

# membuat class DataForm untuk membuat data baru
class DataForm(ModelForm):
    class Meta:
        # merelasikan form dengan model
        model = Data
        # mengeset field apa saja yang akan ditampilkan pada form
        fields = ('nama', 'nim', 'kelas', 'jurusan', 'status_asisten', 'status_data')
        # mengatur teks label untuk setiap field
        labels = {
            'nama': _('Nama'),
            'nim': _('NIM'),
            'kelas': _('Kelas'),
            'jurusan': _('Jurusan'),
            'status_asisten': _('Status Asisten'),
            'status_data': _('Status Keaktifan')
        }
        # mengatur teks pesan error untuk setiap validasi fieldnya
        error_messages = {
            'nama': {
                'required': _("Nama harus diisi."),
            },
            'nim': {
                'required': _("NIM harus diisi."),
            },
            'kelas': {
                'required': _("Kelas harus diisi."),
            },
            'jurusan': {
                'required': _("Jurusan harus diisi."),
            },
        }

mendata/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from django.contrib import messages
# import class Data dari file mendata/models.py
from .models import Data
# import class DataForm dari file mendata/forms.py
from .forms import DataForm

# Membuat View untuk halaman daftar tabel data
def index_view(request):
    # Mengambil semua data dari class "Data" pada models.py
    semua_data = Data.objects.all()
    # Mendefinisikan nilai balik hasil request dari 'semua_data' ke 'datas' 
    # yang akan digunakan pada index.html
    context = {
        'datas': semua_data
    }
    # memparsing data ke template mendata/index.html dan merender nya
    return render(request, 'mendata/index.html', context)

# Membuat View untuk halaman detail 
def detail_view(request, data_id):
# Mengambil data berdasarkan ID
    try:
        # Mengambil data berdasarkan ID dari class "Data" pada models.py
        detail = Data.objects.get(pk=data_id)
        # Mendefinisikan nilai balik hasil request dari 'detail' ke 'data' 
        # yang akan digunakan pada index.html, dan form.html
        context = {
            'data': detail
        }
    except Data.DoesNotExist:
        # Jika data tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Data tidak ditemukan.")
    # parsing data ke template mendata/detail.html dan merendernya
    return render(request, 'mendata/detail.html', context)

# View untuk tambah data
def create_view(request):
    # Mengecek method pada request
    # Jika method-nya adalah POST, maka akan dijalankan
    # proses validasi dan penyimpanan data
    if request.method == 'POST':
        # membuat objek dari class DataForm
        form = DataForm(request.POST)
        # Mengecek validasi form
        if form.is_valid():
            # Membuat Data baru dengan data yang disubmit
            new_data = DataForm(request.POST)
            # Simpan data ke dalam table 
            new_data.save()
            # mengeset pesan sukses dan redirect ke halaman view table
            messages.success(request, 'Sukses Menambah Data baru.')
            return redirect('mendata:index')
    # Jika method-nya bukan POST
    else:
        # membuat objek dari class DataForm
        form = DataForm()
    # merender template form dengan memparsing data form, agar terbaca pada form.html
    return render(request, 'mendata/form.html', {'form': form})

# Membuat View untuk halaman form ubah data
def update_view(request, data_id):
    try:
        # mengambil data yang akan diubah berdasarkan id
        ubah = Data.objects.get(pk=data_id)
    except Data.DoesNotExist:
        # Jika data tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Data tidak ditemukan.")
    # Mengecek method pada request
    # Jika method-nya adalah POST, maka akan dijalankan
    # proses validasi dan penyimpanan data
    if request.method == 'POST':
        form = DataForm(request.POST, instance=ubah)
        if form.is_valid():
            # Simpan perubahan data ke dalam table 
            form.save()
            # mengeset pesan sukses dan redirect ke halaman daftar table
            messages.success(request, 'Sukses Mengubah Data.')
            return redirect('mendata:index')
    # Jika method-nya bukan POST
    else:
        # membuat objek dari class DataForm
        form = DataForm(instance=ubah)
    # merender template form dengan memparsing data form, agar terbaca pada form.html
    return render(request, 'mendata/form.html', {'form': form})

# Membuat View untuk menghapus data 
def delete_view(request, data_id):
    try:
        # mengambil data data_lama yang akan dihapus berdasarkan id
        data_lama = Data.objects.get(pk=data_id)
        # menghapus data dari table 
        data_lama.delete()
        # mengeset pesan sukses dan redirect ke halaman daftar table
        messages.success(request, 'Sukses Menghapus Data.')
        return redirect('mendata:index')
    except Data.DoesNotExist:
        # Jika data tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Data tidak ditemukan.")

mendata/templates/mendata/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Detail Data</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Detail Data</h1>

      <div>
        <a href="{% url 'mendata:index' %}" class="btn btn-success">Kembali ke Daftar</a>
      </div>

      <br>

      <div>
        <h2>{{ data.nama }}</h2>
        
        <h4><span class="badge badge-warning">{{ data.status_asisten }}</span></h3>
        <h4><span class="badge badge-primary">{{ data.status_data }}</span></h3>

        <p>
            <h5>NIM : {{ data.nim }}</h5>
            <h5>Kelas : {{ data.kelas }}</h5>
            <h5>Jurusan : {{ data.jurusan }}</h5>
        </p>

        <a>created : {{ data.created_at }} </a><br/>
        <a>updated : {{ data.updated_at }} </a><br/>
      </div>
  </div>
 
  </body>
</html>

mendata/templates/mendata/form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Data Baru</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Data Form</h1>

      <div>
        <a href="{% url 'mendata:index' %}" class="btn btn-success">Back to List</a>
      </div>

      <br>

      <div>
        <!-- meload package untuk merender form field -->
        {% load widget_tweaks %}

        <form method="post" novalidate>
          <!-- menambahkan csrf field untuk keamanan form -->
          {% csrf_token %}

          <!-- merender semua field form dari objek DataForm -->
          {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              {{ field.label_tag }}

              {% if form.is_bound %}
                {% if field.errors %}
                  {% render_field field class="form-control is-invalid" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control is-valid" %}
                {% endif %}
              {% else %}
                {% render_field field class="form-control" %}
              {% endif %}

              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}

          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
  </div>
 
  </body>
</html>

mendata/templates/mendata/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Aplikasi Mendata Asisten</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Daftar Nama Asisten</h1>

      <div>
        {% if messages %}
        
            
        {% for message in messages %}
            
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  
        <span aria-hidden="true">&times;</span>
              
        </button>
                
        {{ message | safe }}
            
        </div>
            
        {% endfor %}
        
        {% endif %}
        </div>
        
        <!-- tombol untuk ke halaman tambah data -->
        <div>
          
        <a href="{% url 'mendata:create'  %}" class="btn btn-success">Tambah Baru</a>
        </div>

      <br>

      <table class="table table-bordered table-striped">
          <thead>
              <tr>
                  <th width="5%">ID</th>
                  <th width="18%">Nama</th>
                  <th width="10%">NIM</th>
                  <th width="10%">Kelas</th>
                  <th width="13%">Jurusan</th>
                  <th width="15%">Status Asisten</th>
                  <th width="9%">Status</th>
                  <th width="20%">Aksi</th>
              </tr>
          </thead>
          <tbody>
            <!-- Tabel Data-->
            {% if datas %}
              {% for data in datas %}
              <tr>
                  <td>{{ data.id }}</td>
                  <td>{{ data.nama }}</td>
                  <td>{{ data.nim }}</td>
                  <td>{{ data.kelas }}</td>
                  <td>{{ data.jurusan }}</td>
                  <td>{{ data.status_asisten }}</td>
                  <td>{{ data.status_data }}</td>
                  <td>
                      <a href="{% url 'mendata:detail' data.id %}" class="btn btn-warning btn-sm">detail</a>
                      <a href="{% url 'mendata:update' data.id %}" class="btn btn-primary btn-sm">ubah</a>
                      <a href="{% url 'mendata:delete' data.id %}" class="btn btn-danger btn-sm" onclick=" return confirm('Apakah yakin akan menghapus data ini?')">hapus</a>
                  </td>
              </tr>
              {% endfor %}
            {% else %}
              <tr>
                <td colspan="8">Data tidak ditemukan.</td>
              </tr>
            {% endif %}
          </tbody>
      </table>
  </div>
 
  </body>
</html>